### ISSUE TITLE
Issues not loading

### ISSUE THREAD

**Issue by cjwyatt** [sandermvanvliet/SonarCompanion#13]
Having picked a project from the list the Loading issues... label and progress bar appears but the issues never appear.

**Comment by cjwyatt** [comment]
Looks like the company I work for is just running an older version of SonarQube (3.5.1) which has a different API not supported by your extension. Sounds like we'll be upgrading soonish too so pretty much a non-issue now.

**Comment by sandermvanvliet** [comment]
Ok great, could you let me know if that fixed it?
